# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12
fancy_gradle_version=1.1.+

# mod
mod_id=morphtweaked
mod_name=MorphTweaked
mod_version=1.12.2-0.3.0
mod_author=["Lumberjacksparrow","iChun"]
mod_description=Updated fork of Morph for 1.12, with GameStage support
mixin_loader_class=replacememodid.ReplaceMeModNamePlugin

# dependencies
fermiumbooter_version=968474:6848644
jei_version=238222:5846804
